language: python
python:
  - "3.4.3"
env:
- PYTHONPATH=api
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests

before_script:
  python api/manage.py runserver &

script:
  coverage run api/manage.py tests
# coverage run functional_tests.py
